select * from customer limit all

--1 what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--2 which customers used a discount but spent more than average purchase amount ?
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3 which are the top 5 products with the highest average reviw rating ?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4 compare the average purchase amounts between standard and express shipping?

select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by  shipping_type

--DO subscribed customers spend more ? compare average spend and total revenue 
---between subscribe and non subscribe?

select subscription_status,
COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--6 which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(
    100.0 * SUM(CASE WHEN discount_applied ILIKE 'yes' THEN 1 ELSE 0 END) / COUNT(*), 
    2
) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--7 segment customers into new, returning, and loyall based on their total number
-- of previous purchases, and show the count of each segment ?

with customer_type as(
select customer_id, previous_purchases,
CASE
  WHEN previous_purchases = 1 THEN 'NEW'
  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  ELSE 'Loyal'
  END AS customer_segment
from customer
)

select customer_segment, Count(*) as "Number of Customers"
from customer_type
group by customer_segment

--8 what are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category, 
        item_purchased, 
        COUNT(*) as purchase_count,
        DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) as rank
    FROM customer
    GROUP BY category, item_purchased
) as ranked_products
WHERE rank <= 3;

--9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer (>5)'
        ELSE 'Regular Buyer (<=5)'
    END AS buyer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status ILIKE 'Yes' THEN 1 ELSE 0 END) AS subscribers,
    ROUND(100.0 * SUM(CASE WHEN subscription_status ILIKE 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS sub_rate
FROM customer
GROUP BY 1;

--10 what is the revenue contribution of each age group?

   select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;